[www]

; Listen on TCP port so nginx can use fastcgi_pass app:9000
listen = 9000

; Alpine php-fpm default user/group is usually www-data
user = www-data
group = www-data

pm = dynamic
pm.max_children = 20
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Useful debugging/visibility
catch_workers_output = yes

; Ensure env vars from docker are visible
clear_env = no